sudo: false
language: python
python:
  - 3.5
  - 3.6
matrix:
  include:
    - python: 3.7
      dist: xenial  # 3.7 version infomation
      sudo: true
install:
  - pip install poetry
  - poetry install -vvv
script:
  - python -m httptesting.main run_min -v
  - python -m httptesting.main run_min -h