NAME: 基本配置信息


##########################基础URl设置######################################
#ENABLE_BASE_URL为True时，启用基础URL；为Fasle不启用使用case中url
ENABLE_BASE_URL: True
####接口基本url地址####
BASE_URL: http://111.203.187.99:2222

##########################CASE配置#########################################
#请求失败重试设置
RETRY: 
    #失败重试次数
    ReNum: 3 
###########################################################################

##########################执行设置##########################################
#是否启用并发执行,提高速度
ENABLE_EXECUTION: False  
#进程数
EXECUTION_NUM: 4      
#---------------------------------------------------
#启用失败重试功能
ENABLE_RERUN: False  
#失败重试次数
RERUN_NUM: 2  
#---------------------------------------------------
#用例重复执行开关；True启用；False不启用。
ENABLE_REPEAT: False  
REPEAT_NUM: 2
###########################################################################


##########################钉钉设置###########################################
ENABLE_DDING: False
DING_URL: https://oapi.dingtalk.com/robot/send?access_token=
#钉钉机器人token
DD_TOKEN: 3ba50c804de8e286a95948fdbeb3e8b8177f4e32099643c98388c53adc36e3ed
#############################################################################


##########################测试报告设置########################################
#report外网发布地址ip+端口号
REPORT_SERVICE_ENABLE: False
REPORT_HOST: 127.0.0.1
REPORT_PORT: 5001
REPORT_URL: http://60.205.217.8:5002
TESTER_BY: 微生活测试
#############################################################################




###########################邮箱设置###########################################
#发送测试报告,邮件配置

#EMAIL_ENABLE: ###False不启用邮箱，True启用邮邮箱
EMAIL_ENABLE: False

#EMAIL_ENVIRON: ##True启用，系统环境变量配置密码，False为config.yaml配置
EMAIL_ENVIRON: True

#邮箱配置信息
EMAIL:
    #邮件服务器
    Smtp_Server: smtp.exmail.qq.com
    #发送Email邮箱
    Smtp_Sender: lengyaohui.bj@acewill.cn
    #密码，以环境变量配置为先
    Password: --  #最好配置到环境变量
    #邮箱标题
    Msg_Title: 接口自动化测试结果
    #收件人[]多个人用列表存储
    Receivers: ['lengyaohui@163.com']  #收件人
    From: 自动化测试系统
    To: 微生活测试组
##############################################################################



