NAME: 基本配置信息


##########################基础URl设置######################################
#ENABLE_BASE_URL为True时，启用基础URL；为Fasle不启用使用case中url
# True启用； False不启用
ENABLE_BASE_URL: False
####接口基本url地址####
BASE_URL: http://111.111.111.111:2222


##########################执行设置##########################################
#Debug模式输出; True启用； False不启用
ENABLE_DEBUG_MODE: False

#输出模式: True控制台与 False报告模式
ENABLE_EXEC_MODE: False

#是否启用并发执行,提高速度
ENABLE_EXECUTION: False  
#进程数
EXECUTION_NUM: 4      
#---------------------------------------------------
#启用失败重试功能
ENABLE_RERUN: False  
#失败重试次数
RERUN_NUM: 2  
#---------------------------------------------------
#用例重复执行开关；True启用；False不启用。
ENABLE_REPEAT: False  
REPEAT_NUM: 2
###########################################################################


##########################钉钉设置###########################################
#####注意事项###ENABLE_EXEC_MODE: True开启时，控制台不支持钉钉模式。
ENABLE_DDING: False
DING_URL: https://oapi.dingtalk.com/robot/send?access_token=
#钉钉机器人token
DD_TOKEN: 925339305f06c44fe52116e6e8d762797f43894e738990747cdebe24118c2411
#钉钉标题
DING_TITLE: 接口自动化测试
#############################################################################


##########################测试报告设置########################################
#report外网发布地址
REPORT_URL: http://60.60.217.8:5004
#############################################################################




###########################邮箱设置###########################################
#发送测试报告,邮件配置

#EMAIL_ENABLE: ###False不启用邮箱，True启用邮邮箱
EMAIL_ENABLE: False

#邮箱配置信息
EMAIL:
    #邮件服务器
    Smtp_Server: smtp.exmail.qq.com
    #发送Email邮箱
    Smtp_Sender: lengyaohui.bj@acewill.cn
    #密码，以环境变量配置为先;最好配置到环境变量
    Password: --  
    #邮箱标题
    Msg_Title: 接口自动化测试结果
    #收件人[]多个人用列表存储
    Receivers: ['lengyaohui@163.com'] 
    From: 自动化测试系统
    To: 微生活测试组
##############################################################################



